### ISSUE TITLE
[Feature Request] Different textures for item amount in bag

### ISSUE THREAD

**Issue by SnowCutieOwO** [Valorless/HavenBags#10]
For example, I use one texture when the bag is empty, and another three different texture when it's 1/4, 1/2, 3/4 and completely full.
~~Yeah I mean the one in WynnCraft seriously~~

**Comment by Valorless** [comment]
I can look into adding textures based on the bags capacity %.
~~I dont know WynnCraft, but I got an idea for the feature anyway, seriously ;)~~

It shouldn't be the biggest hurdle to overcome :D

**Comment by SnowCutieOwO** [comment]
> I can look into adding textures based on the bags capacity %. ~I dont know WynnCraft, but I got an idea for the feature anyway, seriously ;)~
> 
> It shouldn't be the biggest hurdle to overcome :D

Pretty!
btw is it have the notification? Like if one item is came into the bag and it will show the custom message on ActionBar or Title
:3

**Comment by SnowCutieOwO** [comment]
> I can look into adding textures based on the bags capacity %. ~I dont know WynnCraft, but I got an idea for the feature anyway, seriously ;)~
> 
> It shouldn't be the biggest hurdle to overcome :D

I also got another idea which could fit this plugin, please check in next issue since it's different <3

**Comment by Valorless** [comment]
While adding this, i somehow caused a bug regarding auto-pickup hehe
So might take a little more time to solve that xD

**Comment by SnowCutieOwO** [comment]
> While adding this, i somehow caused a bug regarding auto-pickup hehe So might take a little more time to solve that xD

So hard working and quick response, too amazing <3

**Comment by Valorless** [comment]
Managed to solve the issue, and the texture capacity feature works :)
It glitches if 'keep-bags' is set to false; it straight refuses to apply the texture no matter what i do :(

It'll be available with the release of 1.29.0 ^^
