### ISSUE TITLE
[Feature Request] Arrow bag

### ISSUE THREAD

**Issue by SnowCutieOwO** [Valorless/HavenBags#11]
All arrows inside the bag could be consumed, and will show the amount of remained arrows on actionbar when it's consumed
And if there are multiple bags which could be used as arrow bag, the consume order would be **offhand -> hotbar -> inventory (increasing slot number)** 
For example, there are three arrow bags in inventory, hotbar and offhand, when you use a bow, it will consume the arrow on the offhand bag, then hotbar bag and inventory bag

:3

btw you could also make a potion bag for similar function, like consume a bottle of potion will replace with new one and put empty one back, which could be more useful :3

**Comment by Valorless** [comment]
Needs more research and testing ofc.
But currently I'm unsure how to do this, as in order to draw the bow you need an arrow in your inventory already.
While I can consume an arrow from the bags, I need to figure out how to draw the bow.

**Comment by SnowCutieOwO** [comment]
> Needs more research and testing ofc. But currently I'm unsure how to do this, as in order to draw the bow you need an arrow in your inventory already. While I can consume an arrow from the bags, I need to figure out how to draw the bow.

By sending a packet maybe? For example when holding the bow, replace the offhand to arrow? :3

**Comment by Valorless** [comment]
I'm not confident I can work with packets.
But given the PlayerInteractEvent tends to trigger twice, I can use the first trigger to give the player an arrow, which can then be fired.
Once fired, an arrow is taken from the bag (checked if the bag has an arrow ofc)

**Comment by Valorless** [comment]
I've made it possible to "Draw" arrows from your quivers, but currently having trouble getting the offhand before the rest.

**Comment by Valorless** [comment]
Done ^^
I have some other things I need to work on before releasing.
You can get notified of the update release on Discord https://discord.gg/yyEPqSeXF9, or on Spigot ^^
