### ISSUE TITLE
Incompatibility with CustomAnvil

### ISSUE THREAD

**Issue by alexcrea** [Valorless/HavenBags#12]
Hi, I'm the dev of CustomAnvil I'm here for https://github.com/alexcrea/CustomAnvil/issues/44
I have an idea how to make CustomAnvil compatible, but I just want permission as plugin's license is "All Rights Reserved"

I need either to be able to:
- store on my repo a copy of the plugin,
- store signature of class and methods (only the required for it to work).
- be able to depend on this plugin via maven.

I also want to ask, when it's completed, if I can mark HavenBags as compatible. 
Tell me if you like me to notify you to test CustomAnvil when it should work before I mark it as compatible.

**Comment by Valorless** [comment]
Ofc you can! ^^
I have no problem with this :D
If needed, feel free to suggest changes to [BagUpgrade.java](https://github.com/Valorless/HavenBags/blob/main/src/main/java/valorless/havenbags/BagUpgrade.java); I only ask that it still works without CustomAnvil <3

**Comment by alexcrea** [comment]
Thanks !
Currently, I did not make a pretty way to add compatibility with CustomAnvil on these compatibility issue so can't really be solved on your part/plugin. 
Thanks !

**Comment by alexcrea** [comment]
Closing this as it should work with [this test version](https://github.com/alexcrea/CustomAnvil/releases/tag/v1.7.0-test.4) !

**Comment by Valorless** [comment]
Sweet! ^^
