### ISSUE TITLE
Bags don't open after upgrading to the new version

### ISSUE THREAD

**Issue by RaibuX** [Valorless/HavenBags#2]
I've upgraded the bags from version 1.5 to the most recent version at the moment. All bag UUIDs are still in place, but players can't open their bags. What to do?

**Comment by Valorless** [comment]
Is anything reported in the console?

**Comment by Valorless** [comment]
Had to rush off the pc as I wrote.. sorry.
Could you send me a copy of the config file, and maybe a picture of the /bags folder?
I'll take a look if anything went wrong :)

**Comment by RaibuX** [comment]
[image: image.png]

сб, 25 нояб. 2023 г. в 19:55, Valor ***@***.***>:

**Comment by RaibuX** [comment]
Could it be that we are blocked by Mojang because the files are not
converted to UUIDs? We have hosting in Moscow.

сб, 25 нояб. 2023 г. в 19:55, Valor ***@***.***>:

**Comment by RaibuX** [comment]
![photo_2023-11-25_19-28-25](https://github.com/Valorless/HavenBags/assets/65853662/237505b8-9d77-4ff5-b171-8803c7cac3a4)
https://i.ibb.co/jgW8t3y/filezilla-QZVY33gn-NA.png

**Comment by Valorless** [comment]
Ahh, that is most likely it, though can't be certain.
The UUIDFetcher that HavenBags uses does contact the Mojang API, if Bukkit is unable to provide the UUID.

My guess is that during conversion, players offline did not have their bags changed.
You may still be able to access bag contents via bag commands, to give the players their items back.

You can also try converting bag data again, by removing the variable "config-version" from the config file, or setting it to 0.

**Comment by RaibuX** [comment]
![image](https://github.com/Valorless/HavenBags/assets/65853662/d599b3c2-795f-4382-94e4-3ad4273b4049)
maybe you'r right, but I tried to restore another player's bag, but it first tells me that "No player's bags found" and then shows me the UUID of his bags :D
![image](https://github.com/Valorless/HavenBags/assets/65853662/77786329-6c03-4e9b-b689-47469fe08f27)

**Comment by Valorless** [comment]
I'm sorry to say, but I currently have no plans on updating HavenBags at the moment.
But when I do, I'll add a option to use Usernames instead of UUIDs.
I never considered some regions wouldn't have access to the API, but I'll take it into consideration from now on :)

**Comment by Valorless** [comment]
Greetings RaibuX!
As of the latest version, the only usage of the UUIDFetcher is only within the BagConversion function, which converts bag data from Usernames to UUIDs; And the CommandListener when Bukkit couldn't the desired player on the server. (offline or online)

This should mean that you may be able to use HavenBags without issues now ^^
Although I'd recommend resetting bag data, to ensure no incompatibility :)
