### ISSUE TITLE
I use the bag, all of its contents disappear

### ISSUE THREAD

**Issue by excaliburkim** [Valorless/HavenBags#4]
### What happened?

hello!
I am using it well since you made it. thank you!
I updated from 1.19.2 to 1.20.4, but when I use the bag, all of its contents disappear. Can I check it?

### What was supposed to happen?

I updated from 1.19.2 to 1.20.4, but when I use the bag, all of its contents disappear. Can I check it?

### How do I reproduce this issue?

```bash
1. I updated from 1.19.2 to 1.20.4, but when I use the bag, all of its contents disappear. Can I check it?
```

### Server Version

1.20.4

### Plugin Version

HavenBags-1.6.1.414-SNAPSHOT.jar

### Issue Confirmation

- [X] I have downloaded and tried the latest version of HavenBags and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by Valorless** [comment]
I'm sorry to hear you have issues with the plugin.

When this occurs, does the console say anything?
If not, could you enable debugging for me, and show me what it says? :)

You can check whether it's a bag id issue, by looking at the files in `/plugins/HavenBags/bags/` to see if there's an abundance of data files there shouldn't be.
_(like if you only ever had 1 bag, but there are many data files under your uuid)_
