### ISSUE TITLE
tengo un problema con el plugin

### ISSUE THREAD

**Issue by hecreeper34** [Valorless/HavenBags#7]
### What happened?

lo descargue y ejecute de forma correcta, el problema es que solo los admins que tienen /op pueden abrir las mochilas*

### What was supposed to happen?

*

### How do I reproduce this issue?

```bash
1.
2.
3.
...
```

### Server Version

1.20.4

### Plugin Version

1.7.7.611

### Issue Confirmation

- [X] I have downloaded and tried the latest version of HavenBags and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by Valorless** [comment]
I'd afraid that I don't speak Spanish, so I've used Google Translate to help me :)

To open/use bags, you need to give players the permission `havenbags.use`.
Without it, only server operators can use bags.
You need a permissions manager plugin [LuckPerms](https://www.spigotmc.org/resources/luckperms.28140/) or [Permissions](https://www.spigotmc.org/resources/permissions.87936/).
(There are others two, these were just the ones I found)

**Comment by Valorless** [comment]
Since this issue has been inactive for 5 days, I am going to close it.
If you wish to proceed with this issue, please reopen it again :)
