### ISSUE TITLE
[Suggestion] new1

### ISSUE THREAD

**Issue by dinobossytnew** [Valorless/HavenBags#9]
Possibility to create permissions for slots or rows of backpacks, meaning of 6 so that when 1 user opens the backpack with 1 permission of havenbags.namemochilacustom.2 will have slots from 0 to 17, then if it's possible these users steal it or have more permissions than the other, the backpack will not update, so it will remain at the user's level, but if they return it, items will disappear, which won't happen if the items are stored while those slots are not visible, it will be good.

**Comment by Valorless** [comment]
Greetings!
For some reason the notification for this issue got lost in my mailbox! Very sorry!
I think you joined discord and you mentioned it there as well :)

In v1.15.0 this feature was added ^^
